# rsyslog configuration file
# For more information see https://www.rsyslog.com/doc/configuration/

# use alpine workDirectory
global(
	workDirectory="/var/lib/rsyslog"
)

# Inputs
module(load="imuxsock")  # local system logs (/dev/log)
module(load="imudp")     # remote UDP
module(load="imtcp")     # remote TCP

# Route remote logs to file, local logs to stdout
input(type="imudp" port="514" ruleset="remote_file")
input(type="imtcp" port="514" ruleset="remote_file")
input(type="imuxsock" socket="/dev/log" ruleset="local_stdout")

# Include all config files in /etc/rsyslog.d/.
include(file="/etc/rsyslog.d/*.conf" mode="optional")

# Remote (UDP/TCP) -> dated file by HOSTNAME + program name + message date
template(name="RemoteFileName" type="list") {
  constant(value="/var/log/")
  property(name="hostname" securePath="replace")
  constant(value="-")
  property(name="programname" securePath="replace")
  constant(value="-")
  property(name="timereported" dateFormat="year")
  constant(value="-")
  property(name="timereported" dateFormat="month")
  constant(value="-")
  property(name="timereported" dateFormat="day")
  constant(value=".log")
}

# Remote -> file
ruleset(name="remote_file") {
  action(
    type="omfile"
    dynaFile="RemoteFileName"
  )
  stop
}

# Local -> stdout
ruleset(name="local_stdout") {
  action(
    type="omfile"
    file="/dev/stdout"
  )
  stop
}
