# https://docs.github.com/en/actions/reference/workflows-and-actions

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * 5'
      timezone: "America/Chicago"

name: Check Packages

permissions: read-all

jobs:
  apk-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check for apk package updates
        run: ./tests/apk-upgrade.sh
